const ev = (spec) => spec;

export const EVENTS = [
  ev({
    id: "el_atajo",
    stage: "formacion",
    beat: true,
    years: 3,
    title: "El atajo",
    body: "Un primo ofrece un puesto. Paga ya. La escuela espera «un ciclo más», como si los ciclos no se cobraran.",
    options: [
      {
        id: "study",
        label: "Seguir estudiando",
        hint: "🎓 El título espera. 💰 Cobras menos ahora.",
        punchline: "Invertiste tiempo. El tiempo no da recibo.",
        immediate: { money: -50, happiness: -4, health: 2, status: 6, job: "Estudiante", flagsAdd: ["estudio"] },
      },
      {
        id: "take",
        label: "Tomar el puesto",
        hint: "💰 Cobras ya. 😬 El título se queda atrás.",
        punchline: "Cobras. El título se queda en el anuncio.",
        immediate: { money: 90, income: 18, happiness: 2, health: -4, status: -2, job: "Operativo", flagsAdd: ["atajo"] },
        deferred: { after: 3, type: "event", id: "la_entrevista" },
      },
      {
        id: "both",
        label: "Las dos. Dormir es opcional",
        hint: "⚡ Las dos. 🫀 El cuerpo paga.",
        punchline: "El cuerpo firma el contrato que tú no leíste.",
        immediate: { money: 30, income: 8, happiness: -8, health: -12, job: "Doble turno", flagsAdd: ["agotado", "estudio"] },
      },
    ],
  }),
  ev({
    id: "el_finde",
    stage: "formacion",
    years: 2,
    title: "El único domingo",
    body: "Hay un cumpleaños. Hay un extra. Hay un cuerpo que ya adeuda sueño.",
    options: [
      {
        id: "go",
        label: "Ir. Aparecer cuenta",
        hint: "❤️ Apareces. 💰 El extra se va sin ti.",
        punchline: "Te rieron el chiste. El extra se fue sin ti.",
        immediate: { bonds: 12, money: -25, happiness: 8, status: -2, flagsAdd: ["presente"] },
      },
      {
        id: "extra",
        label: "Cubrir el extra",
        hint: "💰 Cobras el extra. 💔 Sales recortado de la foto.",
        punchline: "El grupo hizo la foto. Saliste recortado.",
        immediate: { money: 55, bonds: -8, happiness: -4, flagsAdd: ["llamada_perdida"] },
      },
      {
        id: "sleep",
        label: "Dormir como un radical",
        hint: "🫀 Duermes. Nadie te aplaude.",
        punchline: "Nadie lo celebra. Tu hígado sí.",
        immediate: { health: 10, happiness: 2, status: -4, bonds: -2 },
      },
    ],
  }),
  ev({
    id: "el_techo",
    stage: "arranque",
    beat: true,
    years: 3,
    title: "El techo",
    body: "El anuncio dice comunidad. El baño discrepa. Tus padres ofrecen el sofá «mientras arrancas».",
    options: [
      {
        id: "humilde",
        label: "Pieza humilde. Tuya",
        hint: "🏠 Tuya. 😬 El baño es de todos.",
        punchline: "Cierras la puerta. Eso ya es política.",
        immediate: { home: 1, money: -70, happiness: -4, expenses: 8 },
      },
      {
        id: "sofa",
        label: "Sofá familiar. Temporal",
        hint: "💰 Ahorras. 😎 Te ven como el que no se fue.",
        punchline: "Temporal entra al diccionario como «hasta los 34».",
        immediate: { home: 0, money: 40, status: -10, bonds: 6, happiness: -2, flagsAdd: ["sofa"] },
      },
      {
        id: "credit",
        label: "Departamento a crédito",
        hint: "🏠 Depto ya. 😬 Vas a deber años.",
        punchline: "El adulto de verdad tiene una app de deudas.",
        immediate: { home: 2, money: -40, debt: 160, status: 12, happiness: 4, expenses: 16, flagsAdd: ["deuda"] },
        deferred: { after: 2, type: "event", id: "la_hipoteca" },
      },
    ],
  }),
  ev({
    id: "primer_contrato",
    stage: "arranque",
    years: 2,
    title: "El contrato sonríe",
    body: "«No pagamos el mercado, pagamos propósito.» El propósito no cubre el transporte.",
    options: [
      {
        id: "sign",
        label: "Firmar. El café es experiencia",
        hint: "😎 Te ven bien. 💰 El sueldo no.",
        punchline: "Tu LinkedIn brilla. Tu cuenta, no.",
        immediate: { job: "Practicante de sinergia", status: 10, money: -20, income: 10, happiness: -4, flagsAdd: ["corp"] },
      },
      {
        id: "ask",
        label: "Pedir un sueldo. Como un loco",
        hint: "😬 Pedir dinero. Ya veremos.",
        punchline: "Te agradecen el feedback. Contratan a tu primo.",
        immediate: { bonds: 4, status: -2, happiness: -2, flagsAdd: ["orgullo"] },
      },
      {
        id: "walk",
        label: "Irse. Hay otros viernes",
        hint: "❤️ Te vas. 💼 El puesto se queda.",
        punchline: "El viernes llega. El organigrama no.",
        immediate: { happiness: 6, income: -6, status: -6, health: 4, flagsAdd: ["libre"] },
      },
    ],
  }),
  ev({
    id: "synergy",
    stage: "construccion",
    beat: true,
    years: 3,
    title: "Lead of Synergy",
    body: "41 slides para decir «sigue así». El título es gratis. El domingo, no.",
    options: [
      {
        id: "lead",
        label: "Aceptar el título",
        hint: "😎 Título nuevo. 🫀 El domingo se acaba.",
        punchline: "Más reuniones. Mismo sueldo. Nombre nuevo.",
        immediate: { job: "Lead of Synergy", status: 16, money: 40, income: 22, happiness: -8, health: -8, bonds: -6, flagsAdd: ["lead"] },
      },
      {
        id: "hours",
        label: "Trabajar 8 horas. Radical",
        hint: "❤️ Sales a tiempo. 😬 Te marcan como raro.",
        punchline: "El sistema lo toma como rebelión.",
        immediate: { happiness: 8, health: 6, status: -6, income: 4, job: "Empleado puntual" },
      },
      {
        id: "raise",
        label: "Pedir dinero, no un pin",
        hint: "💰 Pides plata. 😬 Puede salir mal.",
        punchline: "Te ofrecen fruit Wednesday y un sticker.",
        immediate: { money: 25, happiness: -2, status: 2, flagsAdd: ["pidio"] },
      },
    ],
  }),
  ev({
    id: "semaforo",
    stage: "construccion",
    years: 2,
    title: "El semáforo te evalúa",
    body: "Un anuncio pregunta si ya eres alguien. El autobusero no pregunta nada.",
    options: [
      {
        id: "bus",
        label: "Seguir sin coche de vitrina",
        hint: "💰 Te queda plata. 😎 El semáforo no te ve.",
        punchline: "Ahorras. Pierdes el reflejo en la luna del auto ajeno.",
        immediate: { money: 60, status: -8, happiness: 2, car: 0, flagsAdd: ["casi_lujo"] },
      },
      {
        id: "used",
        label: "Usado con historial honesto",
        hint: "🚗 Ya es tuyo. 😬 El taller también.",
        punchline: "El check engine es tu nuevo roommate.",
        immediate: { car: 2, money: -140, status: 6, expenses: 10, happiness: 6 },
      },
      {
        id: "lease",
        label: "Lease premium. Soft power",
        hint: "😎 Te ven. 😬 36 cuotas te poseen.",
        punchline: "El auto te posee en 36 mensajes del banco.",
        immediate: { car: 4, money: -80, debt: 120, status: 18, expenses: 24, happiness: 4, health: -2, flagsAdd: ["cuotas"] },
        deferred: { after: 2, type: "event", id: "la_cuota" },
      },
    ],
  }),
  ev({
    id: "la_entrevista",
    stage: "construccion",
    years: 1,
    title: "La entrevista que pedía título",
    body: "El puesto es tuyo en la práctica. En el PDF falta una palabra. Esa palabra cuesta años.",
    requireFlags: ["atajo"],
    options: [
      {
        id: "bluff",
        label: "Vender la calle como máster",
        hint: "😬 Vendes la calle. Ya veremos.",
        punchline: "Les gustó el tono. Contrataron al que tenía el sello.",
        immediate: { status: 4, happiness: -6, bonds: 2, flagsAdd: ["rechazo_titulo"] },
      },
      {
        id: "stay",
        label: "Quedarte donde ya cobras",
        hint: "💰 Sigues cobrando. 📉 El techo es bajo.",
        punchline: "El techo es conocido. También es bajo.",
        immediate: { happiness: 2, status: -4, money: 20 },
      },
      {
        id: "night",
        label: "Estudiar de noche. Otra vez",
        hint: "🎓 Otra chance. 🫀 Duermes menos.",
        punchline: "Los años vuelven a la caja. El cuerpo protesta.",
        immediate: { health: -8, happiness: -4, status: 8, flagsAdd: ["estudio"], flagsRemove: ["atajo"] },
      },
    ],
  }),
  ev({
    id: "la_hipoteca",
    stage: "costo",
    beat: true,
    years: 3,
    title: "La hipoteca emocional",
    body: "El departamento no pregunta cómo estás. Pregunta la fecha. Esto viene de aquella firma.",
    requireFlags: ["deuda"],
    options: [
      {
        id: "pay",
        label: "Pagar y callar",
        hint: "❤️ Duermes. 💰 El banco cobra.",
        punchline: "Sigues siendo dueño de una vista. La vista es del banco.",
        immediate: { money: -130, debt: -40, happiness: 4, health: 2 },
      },
      {
        id: "double",
        label: "Doblar. Aún se puede",
        hint: "🔥 Doblas. 😬 Uno de los dos miente.",
        punchline: "El trimestre se entusiasma. Tú también. Uno de los dos miente.",
        immediate: { money: 70, debt: 40, happiness: -8, health: -8, flagsAdd: ["allin"] },
      },
      {
        id: "cut",
        label: "Bajar de peldaño",
        hint: "🏠 Bajas de piso. 😌 Respiras.",
        punchline: "El orgullo adelgaza. El margen respira.",
        immediate: { home: 1, money: 50, debt: -80, status: -10, happiness: 2, expenses: -10, flagsRemove: ["deuda"] },
      },
    ],
  }),
  ev({
    id: "la_cuota",
    stage: "costo",
    years: 2,
    title: "La cuota tiene tu cara",
    body: "El auto sigue lindo. El mensaje del banco no. Recuerdas el semáforo.",
    requireFlags: ["cuotas"],
    options: [
      {
        id: "keep",
        label: "Seguir pagando la foto",
        hint: "😎 La foto queda. 💰 Tú no.",
        punchline: "La foto no se oxida. Tú sí.",
        immediate: { money: -90, status: 4, happiness: -4, debt: -20 },
      },
      {
        id: "sell",
        label: "Devolver el soft power",
        hint: "💰 Te queda margen. 😎 Bajas del pedestal.",
        punchline: "Bajas del pedestal con llave en la mano.",
        immediate: { car: 2, money: 40, status: -12, expenses: -16, debt: -60, flagsRemove: ["cuotas"] },
      },
      {
        id: "deny",
        label: "Ignorar el mensaje",
        hint: "😬 Ignoras el mensaje. Por ahora.",
        punchline: "El silencio también es un cargo.",
        immediate: { happiness: 2, debt: 30, health: -4, flagsAdd: ["mora"] },
      },
    ],
  }),
  ev({
    id: "la_factura",
    stage: "costo",
    years: 3,
    title: "La factura",
    body: "No es un sermón. Es un cargo. Algo que elegiste antes vuelve con intereses.",
    options: [
      {
        id: "body",
        label: "Pagarle al cuerpo",
        hint: "🫀 El médico no acepta KPIs. 💰 Cobras menos.",
        punchline: "El médico no acepta KPIs.",
        immediate: { money: -80, health: 14, happiness: 4, income: -4 },
      },
      {
        id: "work",
        label: "Otro trimestre. Luego existes",
        hint: "💰 Otro trimestre. 💔 Tú llegas después.",
        punchline: "El trimestre llega. Tú llegas después.",
        immediate: { money: 70, health: -14, happiness: -6, bonds: -6, flagsAdd: ["agotado"] },
      },
      {
        id: "call",
        label: "Contestar la llamada pendiente",
        hint: "❤️ Alguien dice tu nombre. ⏳ El trabajo espera.",
        punchline: "Alguien dice tu nombre sin cargo.",
        immediate: { bonds: 16, happiness: 10, money: -20, status: -2, flagsRemove: ["llamada_perdida"], partner: true },
      },
    ],
  }),
  ev({
    id: "el_acta",
    stage: "balance",
    beat: true,
    years: 2,
    title: "El comité de tu vida",
    body: "Nadie pide otro KPI. Piden que firmes el acta. ¿Qué dejas en el expediente?",
    options: [
      {
        id: "numbers",
        label: "Los números. Son claros",
        hint: "😎 Los números se entienden solos.",
        punchline: "El acta entiende columnas. Las personas, no.",
        immediate: { status: 8, happiness: -4, bonds: -4 },
      },
      {
        id: "people",
        label: "Las personas. Son caras",
        hint: "❤️ Las personas. Son caras.",
        punchline: "El margen se queja. La mesa, no.",
        immediate: { bonds: 12, happiness: 8, money: -30, partner: true },
      },
      {
        id: "joke",
        label: "Una frase buena. Es lo que queda",
        hint: "✨ Una frase. Es lo que queda.",
        punchline: "El chiste sobrevive al organigrama.",
        immediate: { happiness: 6, status: 4 },
      },
    ],
  }),
];

export function getEvent(id, catalog = EVENTS) {
  return catalog.find((e) => e.id === id);
}
