export const SEEDS = [
  {
    id: "apellido",
    title: "El apellido",
    body: "Hay un lugar en la mesa de Navidad y un lugar en la empresa del tío. Las dos sillas pesan igual.",
    tension: "¿Vives su plan o el tuyo?",
    opportunity: "Contactos y un colchón.",
    restriction: "La familia cobra en obediencia.",
    start: {
      age: 16,
      money: 380,
      income: 15,
      expenses: 12,
      happiness: 56,
      health: 82,
      bonds: 48,
      status: 42,
      job: "Hijo del organigrama",
      home: 1,
      car: 0,
      debt: 0,
      flags: ["apellido"],
    },
  },
  {
    id: "beca",
    title: "La beca",
    body: "Te prestaron el futuro. El contrato no dice cuántos años se lleva el interés.",
    tension: "¿Estudias o cobras esta semana?",
    opportunity: "Una puerta a educación.",
    restriction: "Cero margen. El tiempo es la deuda.",
    start: {
      age: 17,
      money: 150,
      income: 8,
      expenses: 8,
      happiness: 62,
      health: 78,
      bonds: 44,
      status: 14,
      job: "Becario del país",
      home: 0,
      car: 0,
      debt: 40,
      flags: ["beca"],
    },
  },
  {
    id: "oficio",
    title: "El oficio",
    body: "Cobras el viernes. El ascensor social tiene un letrero de fuera de servicio.",
    tension: "¿Sobrevives o intentas subir?",
    opportunity: "Dinero ahora. Oficio, ritmo, calle.",
    restriction: "Educación y estatus arrancan cerrados.",
    start: {
      age: 16,
      money: 160,
      income: 28,
      expenses: 16,
      happiness: 52,
      health: 74,
      bonds: 38,
      status: 8,
      job: "Ayudante",
      home: 0,
      car: 1,
      debt: 0,
      flags: ["oficio"],
    },
  },
];

export function getSeed(id) {
  return SEEDS.find((s) => s.id === id);
}
