export const SEEDS = [
  {
    id: "apellido",
    title: "La familia",
    emoji: "👨‍👩‍👦",
    body: "Tu familia tiene un buen nombre. Eso abre algunas puertas… y también trae expectativas.",
    tension: "Te conocen. También te vigilan.",
    opportunity: "✨ Te conocen",
    restriction: "😰 + Presión",
    tags: [
      { icon: "✨", text: "Te conocen", kind: "ok" },
      { icon: "💰", text: "+ Oportunidades", kind: "ok" },
      { icon: "😰", text: "+ Presión", kind: "warn" },
    ],
    start: {
      age: 16,
      money: 380,
      income: 15,
      expenses: 12,
      happiness: 56,
      health: 82,
      bonds: 48,
      status: 42,
      job: "Hijo del organigrama",
      home: 1,
      car: 0,
      debt: 0,
      flags: ["apellido"],
    },
  },
  {
    id: "beca",
    title: "La beca",
    emoji: "🎓",
    body: "Puedes estudiar sin pagar. Pero vas a esperar para ganar dinero de verdad.",
    tension: "El futuro te lo prestaron. El presente, no.",
    opportunity: "🎓 + Estudios",
    restriction: "💰 − Dinero ahora",
    tags: [
      { icon: "🎓", text: "+ Estudios", kind: "ok" },
      { icon: "💰", text: "− Dinero ahora", kind: "warn" },
      { icon: "⏳", text: "− Tiempo", kind: "warn" },
    ],
    start: {
      age: 17,
      money: 150,
      income: 8,
      expenses: 8,
      happiness: 62,
      health: 78,
      bonds: 44,
      status: 14,
      job: "Becario del país",
      home: 0,
      car: 0,
      debt: 40,
      flags: ["beca"],
    },
  },
  {
    id: "oficio",
    title: "El oficio",
    emoji: "🔧",
    body: "Puedes empezar a trabajar ya. El dinero llega rápido… crecer será más difícil.",
    tension: "Cobras el viernes. Subir cuesta años.",
    opportunity: "💰 + Dinero ahora",
    restriction: "🎓 − Estudios",
    tags: [
      { icon: "💰", text: "+ Dinero ahora", kind: "ok" },
      { icon: "⚡", text: "+ Experiencia", kind: "ok" },
      { icon: "🎓", text: "− Estudios", kind: "warn" },
    ],
    start: {
      age: 16,
      money: 160,
      income: 28,
      expenses: 16,
      happiness: 52,
      health: 74,
      bonds: 38,
      status: 8,
      job: "Ayudante",
      home: 0,
      car: 1,
      debt: 0,
      flags: ["oficio"],
    },
  },
];

export function getSeed(id) {
  return SEEDS.find((s) => s.id === id);
}
